<?xml version="1.0" ?>
<testsuite errors="0" failures="1" name="tests.TestCyl-20141017152522" tests="4" time="0.004">
	<testcase classname="tests.TestCyl" name="test1D" time="0.004"/>
	<testcase classname="tests.TestCyl" name="test2D" time="0.000"/>
	<testcase classname="tests.TestCyl" name="testTime" time="0.000"/>
	<testcase classname="tests.TestCyl" name="test2DXY" time="0.000">
		<failure message="14.891148063083369 != 0.038176446608393366 within 2 places" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "utest_models.py", line 71, in test2DXY
    0.038176446608393366, 2)
AssertionError: 14.891148063083369 != 0.038176446608393366 within 2 places
]]>		</failure>
	</testcase>
	<system-out>
<![CDATA[CylinderModel2
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
