<?xml version="1.0" ?>
<testsuite errors="0" failures="1" name="tests.TestCyl2-20141017091804" tests="3" time="2.812">
	<testcase classname="tests.TestCyl2" name="test1D" time="2.805"/>
	<testcase classname="tests.TestCyl2" name="testTime" time="0.002"/>
	<testcase classname="tests.TestCyl2" name="test2D" time="0.005">
		<failure message="0.052822284 != 0.038176446608393366 within 2 places" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "utest_models.py", line 91, in test2D
    0.038176446608393366, 2)
AssertionError: 0.052822284 != 0.038176446608393366 within 2 places
]]>		</failure>
	</testcase>
	<system-out>
<![CDATA[CylinderModel2
Choose device(s):
[0] <pyopencl.Device 'Pitcairn' on 'AMD Accelerated Parallel Processing' at 0x2a986b0>
[1] <pyopencl.Device 'Intel(R) Xeon(R) CPU E5-2630 v2 @ 2.60GHz' on 'AMD Accelerated Parallel Processing' at 0x30d1360>
Choice, comma-separated [0]:Set the environment variable PYOPENCL_CTX='' to avoid being asked again.
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
